/**
 * Explore catalog — the trending AI coding agents from OpenRouter's ranking
 * (https://openrouter.ai/apps/category/coding), presented in the Agents tab's
 * "Available to Install" card under an Explore tab so users can discover new
 * agents. Order mirrors the website's ranking exactly (rank 1..N).
 *
 * Each entry either links to a catalogued agent (`catalogId` — install +
 * adapters come from agent-catalog.json) or stands alone as a discovery entry
 * with a website link (web apps) and/or an install command we verified.
 */

export type ExploreKind = 'cli' | 'web' | 'desktop';

export interface ExploreAgent {
  /** Position in OpenRouter's coding-agents ranking (1-based). */
  rank: number;
  name: string;
  /** OpenRouter slug (informational; used for the ranking reference). */
  openrouterSlug: string;
  description: string;
  website: string;
  kind: ExploreKind;
  /** Existing catalog entry id when this agent is adapter-capable + installable. */
  catalogId?: string;
  /** Verified install command for CLI agents not (yet) in the catalog. */
  install?: string;
  /** Logo file in public/logos/ (empty → letter tile fallback). */
  logo?: string;
  /** True when a full provider/model adapter exists in this tool. */
  hasAdapter?: boolean;
}

export const EXPLORE_AGENTS: ExploreAgent[] = [
  {
    rank: 1,
    name: 'Hermes Agent',
    openrouterSlug: 'hermes-agent',
    description:
      'Open-source, self-improving agent by Nous Research — persistent memory, 40+ built-in tools, scheduled automations and subagents.',
    website: 'https://github.com/NousResearch/hermes-agent',
    kind: 'cli',
    install: 'pipx install hermes-agent',
    logo: 'explore-hermes-agent.png',
  },
  {
    rank: 2,
    name: 'Claude Code',
    openrouterSlug: 'claude-code',
    description:
      'Anthropic’s official terminal coding agent — agentic edits, tools and MCP support.',
    website: 'https://claude.com/product/claude-code',
    kind: 'cli',
    catalogId: 'claude-code',
    hasAdapter: true,
  },
  {
    rank: 3,
    name: 'Kilo Code',
    openrouterSlug: 'kilo-code',
    description: 'Open-source VS Code coding agent with orchestrator and architect modes.',
    website: 'https://kilocode.ai',
    kind: 'cli',
    catalogId: 'kilo',
    hasAdapter: true,
  },
  {
    rank: 4,
    name: 'Cline',
    openrouterSlug: 'cline',
    description: 'Autonomous coding agent for VS Code and JetBrains — plans, edits, runs commands.',
    website: 'https://cline.bot',
    kind: 'cli',
    catalogId: 'cline',
    hasAdapter: true,
  },
  {
    rank: 5,
    name: 'Codex',
    openrouterSlug: 'codex',
    description: 'OpenAI’s Codex CLI — local coding agent with sandboxed command execution.',
    website: 'https://developers.openai.com/codex/cli',
    kind: 'cli',
    catalogId: 'codex-cli',
    hasAdapter: true,
  },
  {
    rank: 6,
    name: 'pi',
    openrouterSlug: 'pi',
    description: 'Minimal, extensible terminal coding agent with strong provider flexibility.',
    website: 'https://pi.dev',
    kind: 'cli',
    catalogId: 'pi',
    hasAdapter: true,
  },
  {
    rank: 7,
    name: 'omp',
    openrouterSlug: 'omp',
    description: 'Open-source multipurpose coding agent that runs against any model gateway.',
    website: 'https://omp.sh',
    kind: 'cli',
    catalogId: 'omp',
    hasAdapter: true,
  },
  {
    rank: 8,
    name: 'OpenClaw',
    openrouterSlug: 'openclaw',
    description: 'Self-hosted personal AI assistant gateway with agent sessions and tool use.',
    website: 'https://openclaw.ai',
    kind: 'cli',
    install: 'npm install -g openclaw@latest',
    logo: 'explore-openclaw.png',
  },
  {
    rank: 9,
    name: 'Portkey AI',
    openrouterSlug: 'portkey-ai',
    description: 'AI gateway with observability, guardrails and fallbacks for production agents.',
    website: 'https://portkey.ai',
    kind: 'web',
    logo: 'explore-portkey.png',
  },
  {
    rank: 10,
    name: 'ZCode',
    openrouterSlug: 'zcode',
    description: 'Z.ai’s coding agent for GLM models — terminal-first development workflows.',
    website: 'https://zcode.z.ai',
    kind: 'web',
    logo: 'explore-zcode.png',
  },
  {
    rank: 11,
    name: 'Lemonade',
    openrouterSlug: 'lemonade',
    description: 'Local LLM runtime server exposing OpenAI-compatible endpoints on your machine.',
    website: 'https://lemonade-server.com',
    kind: 'desktop',
  },
  {
    rank: 12,
    name: 'Cursor',
    openrouterSlug: 'cursor',
    description: 'AI-first code editor with a terminal agent (cursor-agent) and cloud sync.',
    website: 'https://cursor.com',
    kind: 'cli',
    catalogId: 'cursor-cli',
    hasAdapter: true,
  },
  {
    rank: 13,
    name: 'OpenHands',
    openrouterSlug: 'openhands',
    description: 'Autonomous software-engineering agent (formerly OpenDevin) with a sandboxed runtime.',
    website: 'https://github.com/All-Hands-AI/OpenHands',
    kind: 'cli',
    install: 'pipx install openhands-ai',
    logo: 'explore-openhands.png',
  },
  {
    rank: 14,
    name: 'Strix',
    openrouterSlug: 'strix',
    description: 'Autonomous security agent that pentests your code and infrastructure.',
    website: 'https://strix.ai',
    kind: 'cli',
    install: 'pipx install strix',
  },
  {
    rank: 15,
    name: 'Zed Editor',
    openrouterSlug: 'zed-editor',
    description: 'High-performance collaborative code editor with built-in AI agent panel.',
    website: 'https://zed.dev',
    kind: 'desktop',
    catalogId: 'zed',
    hasAdapter: true,
  },
  {
    rank: 16,
    name: 'Ito',
    openrouterSlug: 'ito',
    description: 'AI dictation and voice-control app for the desktop.',
    website: 'https://ito.sh',
    kind: 'desktop',
  },
  {
    rank: 17,
    name: 'GDevelop',
    openrouterSlug: 'gdevelop',
    description: 'No-code game engine with AI-assisted game creation.',
    website: 'https://gdevelop.io',
    kind: 'desktop',
    logo: 'explore-gdevelop.png',
  },
  {
    rank: 18,
    name: 'Command Code',
    openrouterSlug: 'commandcode',
    description: 'Terminal-native coding agent with repo-wide context.',
    website: 'https://commandcode.ai',
    kind: 'web',
  },
  {
    rank: 19,
    name: 'Proto Agent',
    openrouterSlug: 'proto-agent',
    description: 'Autonomous engineering agent by ERP.ai.',
    website: 'https://proto.erp.ai',
    kind: 'web',
    logo: 'explore-proto.png',
  },
  {
    rank: 20,
    name: 'Studs.gg',
    openrouterSlug: 'studsgg',
    description: 'Coding-agent arena — compare agents on real tasks.',
    website: 'https://studs.gg',
    kind: 'web',
    logo: 'explore-studsgg.png',
  },
  {
    rank: 21,
    name: 'Roo Code',
    openrouterSlug: 'roo-code',
    description: 'AI dev team in your editor — mode-based agents (architect, code, debug).',
    website: 'https://roocode.com',
    kind: 'cli',
    catalogId: 'roo',
    hasAdapter: true,
  },
  {
    rank: 22,
    name: 'goose',
    openrouterSlug: 'goose',
    description: 'Block’s open-source extensible AI agent that automates engineering tasks.',
    website: 'https://block.github.io/goose/',
    kind: 'cli',
    catalogId: 'goose',
    hasAdapter: true,
  },
  {
    rank: 23,
    name: 'Qwen Code',
    openrouterSlug: 'qwen-code',
    description: 'Alibaba’s CLI coding agent tuned for Qwen models.',
    website: 'https://qwenlm.github.io/qwen-code-docs/',
    kind: 'cli',
    catalogId: 'qwen',
    hasAdapter: true,
  },
  {
    rank: 24,
    name: 'CodeGPT',
    openrouterSlug: 'codegpt',
    description: 'AI coding assistant platform for IDEs and teams.',
    website: 'https://codegpt.co',
    kind: 'web',
    logo: 'explore-codegpt.png',
  },
  {
    rank: 25,
    name: 'Itonami',
    openrouterSlug: 'itonami',
    description: 'Japanese-language coding agent by KotobaLabs.',
    website: 'https://itonami.cloud',
    kind: 'web',
    logo: 'explore-itonami.png',
  },
  {
    rank: 26,
    name: 'mimocode',
    openrouterSlug: 'mimocode',
    description: 'Xiaomi’s MiMo coding agent — terminal AI pair programmer.',
    website: 'https://mimo.xiaomi.com/coder',
    kind: 'cli',
    catalogId: 'mimo',
    hasAdapter: true,
  },
  {
    rank: 27,
    name: 'pi (OpenRouter Plus)',
    openrouterSlug: 'pi-openrouter-plus',
    description: 'Community fork of pi preconfigured for OpenRouter.',
    website: 'https://github.com/olixis/pi-openrouter-plus',
    kind: 'cli',
    catalogId: 'pi',
    hasAdapter: true,
  },
  {
    rank: 28,
    name: 'Letaido',
    openrouterSlug: 'letaido',
    description: 'AI agent workspace for code and docs.',
    website: 'https://letaido.com',
    kind: 'web',
    logo: 'explore-letaido.png',
  },
  {
    rank: 29,
    name: 'Digen AI',
    openrouterSlug: 'digen-ai',
    description: 'Hosted autonomous agent platform.',
    website: 'https://agent.digen.ai',
    kind: 'web',
  },
  {
    rank: 30,
    name: 'Letta',
    openrouterSlug: 'letta',
    description: 'Stateful agents framework (formerly MemGPT) with persistent memory and tools.',
    website: 'https://letta.com',
    kind: 'cli',
    install: 'pipx install letta',
  },
  {
    rank: 31,
    name: 'Crush',
    openrouterSlug: 'crush',
    description: 'Charm’s terminal-based AI coding agent with a beautiful TUI.',
    website: 'https://charm.land/crush',
    kind: 'cli',
    catalogId: 'crush',
    hasAdapter: true,
  },
  {
    rank: 32,
    name: 'Mage',
    openrouterSlug: 'mage',
    description: 'AI-powered platform for building full-stack apps from prompts.',
    website: 'https://mage.build',
    kind: 'web',
  },
  {
    rank: 33,
    name: 'Agent Zero',
    openrouterSlug: 'agent-zero',
    description: 'General-purpose autonomous agent framework that grows with use (Docker-based).',
    website: 'https://agentzero.ai',
    kind: 'cli',
    install: 'docker run -p 50001:80 agent0ai/agent-zero:latest',
    logo: 'explore-agent-zero.png',
  },
  {
    rank: 34,
    name: 'Hermes Web UI',
    openrouterSlug: 'hermes-web-ui',
    description: 'Web studio for the Hermes agent — sessions, tools and automations.',
    website: 'https://hermes-studio.ai',
    kind: 'web',
    logo: 'explore-hermes-agent.png',
  },
  {
    rank: 35,
    name: 'PostQode',
    openrouterSlug: 'postqode',
    description: 'AI QA agent that explores and tests web applications.',
    website: 'https://postqode.ai',
    kind: 'web',
    logo: 'explore-postqode.png',
  },
  {
    rank: 36,
    name: 'OpenMed Agent',
    openrouterSlug: 'openmed-agent',
    description: 'Healthcare-focused autonomous agent.',
    website: 'https://agent.openmed.life',
    kind: 'web',
  },
  {
    rank: 37,
    name: 'Multi-Agent Arena',
    openrouterSlug: 'multi-agent-arena',
    description: 'Olam Labs’ arena for benchmarking multiple agents head-to-head.',
    website: 'https://olamlabs.ai',
    kind: 'web',
    logo: 'explore-olamlabs.png',
  },
  {
    rank: 38,
    name: 'Favur',
    openrouterSlug: 'favur',
    description: 'AI engineering agent for code review and delivery.',
    website: 'https://favur.dev',
    kind: 'web',
    logo: 'explore-favur.png',
  },
  {
    rank: 39,
    name: 'Trenzel',
    openrouterSlug: 'trenzel',
    description: 'AI agent for web development workflows.',
    website: 'https://trenzel.com',
    kind: 'web',
  },
  {
    rank: 40,
    name: 'AgentField AI',
    openrouterSlug: 'agentfield',
    description: 'Platform for deploying and orchestrating agent workflows.',
    website: 'https://agentfield.ai',
    kind: 'web',
    logo: 'explore-agentfield.png',
  },
  {
    rank: 41,
    name: 'Panwright',
    openrouterSlug: 'panwright',
    description: 'AI pair programmer for complex refactors.',
    website: 'https://panwright.com',
    kind: 'web',
    logo: 'explore-panwright.png',
  },
  {
    rank: 42,
    name: 'Agent37',
    openrouterSlug: 'agent37',
    description: 'Agentic gaming and development platform.',
    website: 'https://www.agent37.com',
    kind: 'web',
    logo: 'explore-agent37.png',
  },
  {
    rank: 43,
    name: 'Traycer',
    openrouterSlug: 'traycer',
    description: 'AI code-review agent that plans and reviews pull requests.',
    website: 'https://traycer.ai',
    kind: 'web',
    logo: 'explore-traycer.png',
  },
  {
    rank: 44,
    name: 'Kern Agent',
    openrouterSlug: 'kern-agent',
    description: 'Open-source research agent for code intelligence.',
    website: 'https://github.com/oguzbilgic/kern-ai',
    kind: 'web',
  },
  {
    rank: 45,
    name: 'camelAI',
    openrouterSlug: 'camelai',
    description: 'AI data-analysis and engineering agent.',
    website: 'https://camelai.dev',
    kind: 'web',
    logo: 'explore-camelai.png',
  },
  {
    rank: 46,
    name: 'Minara',
    openrouterSlug: 'minara',
    description: 'Autonomous agent for shipping projects end-to-end.',
    website: 'https://minara.ai',
    kind: 'web',
    logo: 'explore-minara.png',
  },
  {
    rank: 47,
    name: 'Verdent',
    openrouterSlug: 'verdent',
    description: 'AI development platform with orchestrated agent teams.',
    website: 'https://www.verdent.ai',
    kind: 'web',
    logo: 'explore-verdent.png',
  },
  {
    rank: 48,
    name: 'JONI',
    openrouterSlug: 'joni',
    description: 'AI agent assistant for developers.',
    website: 'https://joni.ai',
    kind: 'web',
    logo: 'explore-joni.png',
  },
  {
    rank: 49,
    name: 'Aexol.ai',
    openrouterSlug: 'aexol',
    description: 'AI agent for product engineering.',
    website: 'https://aexol.ai',
    kind: 'web',
  },
  {
    rank: 50,
    name: 'Raven Agent',
    openrouterSlug: 'raven-agent',
    description: 'Evermind’s autonomous research and coding agent.',
    website: 'https://raven.evermind.ai',
    kind: 'web',
    logo: 'explore-raven.png',
  },
];
